"""empty message

Revision ID: 456ae0e754d9
Revises: 29a7f33ca679
Create Date: 2024-03-03 11:05:25.798039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '456ae0e754d9'
down_revision: Union[str, None] = '29a7f33ca679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('translate', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'translate')
    # ### end Alembic commands ###
