"""empty message

Revision ID: ef1c9b0d3bc7
Revises: 318aa24714e4
Create Date: 2024-03-13 20:26:21.634191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1c9b0d3bc7'
down_revision: Union[str, None] = '318aa24714e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification')
    # ### end Alembic commands ###
